import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LocalNotifications} from '@capacitor/local-notifications';
import {CalendarDays,CheckCircle2,Clock3,GraduationCap,LayoutDashboard,ListTodo,Plus,Settings,Trash2,ChevronLeft,Bell,Sun, Moon} from 'lucide-react';
import './styles.css';

type Tab='home'|'schedule'|'subjects'|'grades'|'tasks';
type Task={id:number;title:string;due:string;done:boolean;kind:'واجب'|'مشروع'};
type Subject={id:number;name:string;credit:number;grade:number;semester:string};
type Session={day:number;start:string;end:string;name:string;type:'CM'|'TD'|'TP';room:string};
const days=['الأحد','الإثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];
const seedSessions:Session[]=[{day:0,start:'08:30',end:'10:00',name:'آلات كهربائية',type:'CM',room:'المدرج A'},{day:0,start:'10:15',end:'11:45',name:'إلكترونيك',type:'TD',room:'قاعة 04'},{day:1,start:'09:00',end:'10:30',name:'دارات كهربائية',type:'TP',room:'المخبر 2'},{day:2,start:'08:30',end:'10:00',name:'كهرومغناطيسية',type:'CM',room:'المدرج B'},{day:3,start:'13:00',end:'14:30',name:'تحليل 3',type:'TD',room:'قاعة 11'},{day:4,start:'10:00',end:'11:30',name:'احتمالات وإحصاء',type:'CM',room:'المدرج A'}];
const seedSubjects:Subject[]=[{id:1,name:'دارات كهربائية',credit:4,grade:13,semester:'السداسي 3'},{id:2,name:'إلكترونيك',credit:4,grade:14,semester:'السداسي 3'},{id:3,name:'كهرومغناطيسية',credit:3,grade:11,semester:'السداسي 3'},{id:4,name:'تحليل 3',credit:3,grade:12,semester:'السداسي 3'},{id:5,name:'احتمالات وإحصاء',credit:2,grade:15,semester:'السداسي 3'},{id:6,name:'آلات كهربائية',credit:4,grade:10,semester:'السداسي 3'}];
const seedTasks:Task[]=[{id:1,title:'حل سلسلة تمارين الدارات 02',due:'2026-09-18',done:false,kind:'واجب'},{id:2,title:'تقرير تجربة الإلكترونيك',due:'2026-09-21',done:false,kind:'مشروع'}];
const seedExams=[{name:'امتحان الدارات الكهربائية',date:'2026-10-12'},{name:'امتحان الإلكترونيك',date:'2026-10-18'}];
function load<T>(key:string, fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch{return fallback}}
function App(){
 const [tab,setTab]=useState<Tab>('home'); const [dark,setDark]=useState(load('dark',true)); const [subjects,setSubjects]=useState<Subject[]>(load('subjects',seedSubjects)); const [tasks,setTasks]=useState<Task[]>(load('tasks',seedTasks)); const [newTask,setNewTask]=useState(''); const [newDue,setNewDue]=useState(new Date(Date.now()+86400000*3).toISOString().slice(0,10)); const [sim,setSim]=useState<number|null>(null);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('dark',JSON.stringify(dark))},[dark]); useEffect(()=>localStorage.setItem('subjects',JSON.stringify(subjects)),[subjects]); useEffect(()=>localStorage.setItem('tasks',JSON.stringify(tasks)),[tasks]);
 const avg=useMemo(()=>subjects.reduce((a,s)=>a+s.grade*s.credit,0)/subjects.reduce((a,s)=>a+s.credit,0),[subjects]); const simulated=sim===null?avg:subjects.reduce((a,s)=>a+(s.id===sim?s.grade:s.grade)*s.credit,0)/subjects.reduce((a,s)=>a+s.credit,0); const today=new Date().getDay(); const todaySessions=seedSessions.filter(s=>s.day===today); const nextTask=tasks.filter(t=>!t.done).sort((a,b)=>a.due.localeCompare(b.due))[0];
 const notify=async(task:Task)=>{try{await LocalNotifications.requestPermissions();await LocalNotifications.schedule({notifications:[{id:task.id+100,title:'تذكير جامعي',body:task.title+' — موعد التسليم قريب',schedule:{at:new Date(task.due+'T09:00:00')}}]})}catch{alert('التنبيهات تعمل بعد تثبيت APK ومنح إذن الإشعارات.')}};
 const addTask=()=>{if(!newTask.trim())return;const t={id:Date.now(),title:newTask,due:newDue,done:false,kind:'واجب' as const};setTasks([t,...tasks]);setNewTask('')};
 return <div className="app"><header><div className="brand"><div className="logo"><GraduationCap size={24}/></div><div><h1>حياتي الجامعية</h1><small>السنة الثانية · إلكتروتقني</small></div></div><button className="icon-btn" onClick={()=>setDark(!dark)} aria-label="الوضع"><span>{dark?<Sun size={19}/>:<Moon size={19}/>}</span></button></header>
 <main>{tab==='home'&&<Home avg={avg} nextTask={nextTask} todaySessions={todaySessions} exams={seedExams} setTab={setTab}/>} {tab==='schedule'&&<Schedule/>} {tab==='subjects'&&<Subjects subjects={subjects} setSubjects={setSubjects}/>} {tab==='grades'&&<Grades subjects={subjects} sim={sim} setSim={setSim} simulated={simulated}/>} {tab==='tasks'&&<Tasks tasks={tasks} setTasks={setTasks} newTask={newTask} setNewTask={setNewTask} newDue={newDue} setNewDue={setNewDue} addTask={addTask} notify={notify}/>}</main>
 <nav>{([["home",LayoutDashboard,'الرئيسية'],["schedule",CalendarDays,'الجدول'],["subjects",GraduationCap,'المقاييس'],["grades",Clock3,'المعدل'],["tasks",ListTodo,'المهام']] as const).map(([id,Icon,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><Icon size={20}/><span>{label}</span></button>)}</nav></div>
}
function Home({avg,nextTask,todaySessions,exams,setTab}:{avg:number;nextTask?:Task;todaySessions:Session[];exams:{name:string;date:string}[];setTab:(t:Tab)=>void}){const countdown=(d:string)=>Math.max(0,Math.ceil((new Date(d).getTime()-Date.now())/86400000));return <><section className="hero"><div><p>صباح الخير، طالب السنة الثانية</p><h2>نظّم يومك بذكاء</h2><span className="muted">كل ما تحتاجه لدراستك في مكان واحد.</span></div><div className="avg-big"><b>{avg.toFixed(2)}</b><span>/ 20</span><small>المعدل الحالي</small></div></section><div className="stats"><button onClick={()=>setTab('grades')}><b>{avg.toFixed(2)}</b><span>المعدل</span></button><button onClick={()=>setTab('schedule')}><b>{todaySessions.length}</b><span>حصص اليوم</span></button><button onClick={()=>setTab('tasks')}><b>{exams.length}</b><span>امتحانات قادمة</span></button></div><section className="section-head"><h3>حصص اليوم</h3><button className="link" onClick={()=>setTab('schedule')}>عرض الجدول <ChevronLeft size={16}/></button></section><div className="cards">{todaySessions.length?todaySessions.map((s,i)=><div className={'session '+(i===0?'current':'')} key={i}><div className="time">{s.start}<small>{s.end}</small></div><div className="session-info"><b>{s.name}</b><span>{s.type} · {s.room}</span></div>{i===0&&<em>قريبة</em>}</div>):<div className="empty">لا توجد حصص اليوم. يوم موفق!</div>}</div><section className="section-head"><h3>نظرة سريعة</h3></section><div className="quick-grid"><div className="info-card"><Bell size={19}/><span>أقرب واجب</span><b>{nextTask?.title||'لا يوجد'}</b><small>{nextTask?nextTask.due:'—'}</small></div><div className="info-card exam"><Clock3 size={19}/><span>الامتحان القادم</span><b>{exams[0].name}</b><small>بعد {countdown(exams[0].date)} يوم</small></div></div></>}
function Schedule(){const [day,setDay]=useState(new Date().getDay());return <><PageTitle title="الجدول الأسبوعي" sub="محاضراتك، أعمالك الموجهة والتطبيقية"/><div className="day-tabs">{days.slice(0,6).map((d,i)=><button className={day===i?'chosen':''} onClick={()=>setDay(i)} key={d}>{d.slice(0,3)}</button>)}</div><div className="cards">{seedSessions.filter(s=>s.day===day).map((s,i)=><div className={'session '+(i===0?'current':'')} key={i}><div className="time">{s.start}<small>{s.end}</small></div><div className="session-info"><b>{s.name}</b><span>{s.type} · {s.room}</span></div><span className="tag">{s.type}</span></div>)}{!seedSessions.some(s=>s.day===day)&&<div className="empty">لا توجد حصص مبرمجة لهذا اليوم.</div>}</div><p className="hint">يمكن تعديل الحصص لاحقاً بإضافة شاشة الإعدادات أو ربطها بقاعدة Supabase.</p></>}
function Subjects({subjects,setSubjects}:{subjects:Subject[];setSubjects:React.Dispatch<React.SetStateAction<Subject[]>>}){return <><PageTitle title="المقاييس" sub="اضغط على النقطة لتعديلها يدوياً"/><div className="cards">{subjects.map(s=><div className="subject" key={s.id}><div><b>{s.name}</b><span>{s.semester} · معامل {s.credit}</span></div><input type="number" min="0" max="20" step="0.25" value={s.grade} onChange={e=>setSubjects(xs=>xs.map(x=>x.id===s.id?{...x,grade:Number(e.target.value)}:x))}/><span>/20</span></div>)}</div><button className="primary" onClick={()=>setSubjects([...subjects,{id:Date.now(),name:'مقياس جديد',credit:2,grade:0,semester:'السداسي 3'}])}><Plus size={18}/> إضافة مقياس</button></>}
function Grades({subjects,sim,setSim,simulated}:{subjects:Subject[];sim:number|null;setSim:(x:number|null)=>void;simulated:number}){return <><PageTitle title="حاسبة المعدل" sub="النظام الجزائري · المعدل على 20 بالمعاملات"/><div className="grade-hero"><span>المعدل المحسوب</span><b>{simulated.toFixed(2)} <small>/ 20</small></b><div className="progress"><i style={{width:`${Math.min(100,simulated*5)}%`}}/></div></div><div className="simulation"><h3>محاكاة ماذا لو؟</h3><p>اختر مقياساً لرؤية أثر تحسينه. عدّل النقطة في صفحة المقاييس.</p><select value={sim??''} onChange={e=>setSim(e.target.value?Number(e.target.value):null)}><option value="">المعدل الحالي</option>{subjects.map(s=><option value={s.id} key={s.id}>{s.name} · {s.grade}/20</option>)}</select></div><div className="formula">المعدل = مجموع (النقطة × المعامل) ÷ مجموع المعاملات</div></>}
function Tasks({tasks,setTasks,newTask,setNewTask,newDue,setNewDue,addTask,notify}:{tasks:Task[];setTasks:React.Dispatch<React.SetStateAction<Task[]>>;newTask:string;setNewTask:(s:string)=>void;newDue:string;setNewDue:(s:string)=>void;addTask:()=>void;notify:(t:Task)=>void}){return <><PageTitle title="المهام والواجبات" sub="قائمة يومية بسيطة مع تذكيرات محلية"/><div className="add-task"><input placeholder="أضف مهمة جديدة..." value={newTask} onChange={e=>setNewTask(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addTask()}/><input className="date-input" type="date" value={newDue} onChange={e=>setNewDue(e.target.value)}/><button onClick={addTask}><Plus size={20}/></button></div><div className="cards">{tasks.map(t=><div className={'task '+(t.done?'done':'')} key={t.id}><button className="check" onClick={()=>setTasks(xs=>xs.map(x=>x.id===t.id?{...x,done:!x.done}:x))}>{t.done?<CheckCircle2 size={22}/>:<span/>}</button><div><b>{t.title}</b><span>{t.kind} · التسليم {t.due}</span></div><button className="bell" onClick={()=>notify(t)}><Bell size={18}/></button><button className="delete" onClick={()=>setTasks(xs=>xs.filter(x=>x.id!==t.id))}><Trash2 size={17}/></button></div>)}</div></>}
function PageTitle({title,sub}:{title:string;sub:string}){return <div className="page-title"><h2>{title}</h2><p>{sub}</p></div>}
createRoot(document.getElementById('root')!).render(<App/>);
